version: '3.9'
services:
  db:
    image: mongo:5.0.7
    container_name: share_mongo_db
    volumes:
      - ./:/app
    restart: always
    ports:
      - 27017:27017

networks:
  default:
    name: share_mongo_net